# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-21 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='time',
            new_name='timestamp',
        ),
    ]
